var UpdateInterval=1E3,smooth=5,smoothType=0,data=[],einheit="%",fag_Average=[0];
$(function(){function e(){var p=data.length,q=$("#IDdataSelect").val(),d=parent.top.$("#"+q).val(),b=moment();var c=UpdateInterval/1E3;c=1==document.getElementById("ID_Compensate").checked?smooth>=c?moment().subtract(Math.ceil(smooth*c/2-c),"s"):moment().subtract(Math.floor(smooth*c/2-.5*c),"s"):b;-1==q.indexOf("D")?(l.series.lines.steps=!1,a.series.lines.steps=!1,document.getElementById("IDsmooth").removeAttribute("disabled")):(d&=1,l.series.lines.steps=!0,a.series.lines.steps=!0,document.getElementById("IDsmooth").setAttribute("disabled",
"disabled"));3600<p&&data.shift();240<h.length&&(h.shift(),n.shift());"undefined"===typeof d&&(d=0);if(0!==smooth){fag_Average.unshift(parseFloat(d));fag_Average.length>smooth?fag_Average.pop():fag_Average.unshift(d);switch(smoothType){case 0:var f=ss.mean(fag_Average);break;case 1:f=ss.median(fag_Average);break;case 2:f=ss.rootMeanSquare(fag_Average);break;case 3:try{f=ss.harmonicMean(fag_Average)}catch(r){}break;case 4:try{f=ss.geometricMean(fag_Average)}catch(r){}break;case 5:f=ss.mode(fag_Average)}n.push([c,
f])}else fag_Average=[];d<k&&(k=d);d>g&&(g=d);a.grid.markings=[{yaxis:{from:g,to:g},color:t,lineWidth:2},{yaxis:{from:k,to:k},color:u,lineWidth:2}];data.push([b,d]);h.push([b,d]);0==m&&(plot=$.plot("#chart",[{data:h,options:a},{data:n,lines:{fill:!1},points:{show:!1}}],a),overview=$.plot("#overview",[data],l),$(".cur_value").html(Round(d,2)+"&nbsp;"+einheit),$(".min_value").html(Round(k,2)+"&nbsp;"+einheit),$(".max_value").html(Round(g,2)+"&nbsp;"+einheit),$(".avg_value").html(Round(f,2)+"&nbsp;"+
einheit),$("#DataSize").text(p+" / "+moment.utc((3600-p)*UpdateInterval).format("H:mm:ss")));setTimeout(e,UpdateInterval)}function b(){overview=$.plot("#overview",[data],l);plot=$.plot("#chart",[h],a)}function c(){$("#IDPause").hasClass("active")?m||$("#IDPauseIcon").removeClass("fa-play").addClass("fa-pause"):$("#IDPauseIcon").removeClass("fa-pause").addClass("fa-play")}var h=[],n=[],m=!1;var k=Number.MAX_VALUE;var g=Number.MIN_VALUE;(function(){var a,b=!1;parent.top.$("#IDdata").find("input").each(function(){id=
this.id;-1===id.indexOf("DI")&&-1===id.indexOf("DO")&&-1===id.indexOf("AI")&&-1===id.indexOf("AO")||-1!=id.indexOf("_")||(a=document.createElement("option"),a.text=id,a.value=id,0==b&&-1!=id.indexOf("AI")&&(a.selected="selected",b=!0),document.getElementById("IDdataSelect").add(a))})})();var v=$("#Color_Curve").css("background-color"),w=$("#Color_Curve_Avg").css("background-color"),t=$("#Color_Curve_Min").css("background-color"),u=$("#Color_Curve_Max").css("background-color"),a={yaxis:{autoScale:"loose",
autoScaleMargin:.1,growOnly:!0,datamin:0,datamax:100,position:"right"},xaxis:{timezone:"browser",mode:"time",timeformat:"%H:%M:%S",minTickSize:[1,"second"]},series:{lines:{show:!0,lineWidth:2,fill:!0,steps:!1,fillColor:{colors:[{opacity:0},{opacity:.05},{opacity:.4}]},zero:!1},splines:{show:!1,tension:.35,lineWidth:2,fill:.1},points:{show:!0,radius:2,symbol:"circle"},shadowSize:0},colors:[v,w],selection:{mode:"x"},grid:{hoverable:!0,markings:[],color:"#aaa",borderColor:"#00000000"}},l={series:{lines:{show:!0,
lineWidth:1,fill:!0,fillColor:{colors:[{opacity:0},{opacity:.1},{opacity:.4}]},steps:!1,zero:!1},shadowSize:0},xaxis:{timeformat:"%H:%M:%S",mode:"time",minTickSize:[1,"minute"]},yaxis:{ticks:[],autoscaleMargin:.1},selection:{mode:"x"},colors:["#bbb"],grid:{color:"#aaa",borderColor:"#00000000"}};$("<div id='tooltip'></div>").css({position:"absolute",display:"none",padding:"0.5em",color:"white","text-align":"center","border-radius":"0.3em","background-color":"black"}).appendTo("body");$("#chart").bind("plothover",
function(a,b,d){b.x&&b.y&&(d?(a=d.datapoint[0].toFixed(2),b=d.datapoint[1].toFixed(2),$("#tooltip").html('<span class="value_big">'+b+"</span><br>"+moment.unix(a/1E3).format("HH:mm:ss")).css({top:d.pageY+5,left:d.pageX+5}).fadeIn(500)):$("#tooltip").hide())});$("#chart").bind("plothovercleanup",function(a,b,d){$("#tooltip").hide()});$("#chart").bind("plotselected",function(b,e){plot=$.plot("#chart",[data],$.extend(!0,{},a,{xaxis:{min:e.xaxis.from,max:e.xaxis.to}}));m=!0;$("#IDPause").addClass("active");
c();overview.setSelection(e,!0)});$("#overview").bind("plotselected",function(a,b){plot.setSelection(b)});setTimeout(e,UpdateInterval);$("#ID_AutoZoom").on("change",function(){var c=$('option[name="AutoZoom"]:selected',"#ID_AutoZoom").val();a.yaxis.min="0";a.yaxis.max="100";switch(c){case "0":a.yaxis.autoScale="none";break;case "10":a.yaxis.autoScaleMargin=.1;a.yaxis.autoScale="loose";break;case "11":a.yaxis.autoScale="exact";break;case "20":a.yaxis.autoScaleMargin=.1;a.yaxis.autoScale="loose";a.yaxis.growOnly=
!0;break;case "21":a.yaxis.autoScale="exact";a.yaxis.growOnly=!0;break;case "30":a.yaxis.autoScale="sliding-window"}b()});$("#IDsmooth").click(function(){a.series.lines.show?(a.series.lines.show=!1,a.series.splines.show=!0):(a.series.lines.show=!0,a.series.splines.show=!1);b()});$("#IDfill").click(function(){a.series.lines.fill=a.series.lines.fill?!1:!0;l.series.lines.fill=a.series.lines.fill;a.series.splines.fill=0<a.series.splines.fill?0:.15;b()});$("#IDShowPoints").click(function(){a.series.points.show=
a.series.points.show?!1:!0;b()});$("#IDmaxReset").click(function(){mid=g=0});$("#IDminReset").click(function(){k=g;mid=0});$("#IDPause").click(function(){m=m?!1:!0;c()});$("#IDDataReset").click(function(){h=[];n=[];fag_Average=[];data=[];b()});$(window).resize(function(){plot.resize();plot.setupGrid();plot.draw();overview.resize();overview.setupGrid();overview.draw()})});jQuery.browser={};
(function(){jQuery.browser.msie=!1;jQuery.browser.version=0;navigator.userAgent.match(/MSIE ([0-9]+)\./)&&(jQuery.browser.msie=!0,jQuery.browser.version=RegExp.$1)})();
var UpdateIntervalOptions=function(){for(var e=1;121>e;e++)oOption=document.createElement("option"),oOption.text=e,oOption.value=1E3*e,document.getElementById("updateInterval").add(oOption)},Download=function(){for(var e=[],b=0,c=data.length;b<c;++b)e.push(data[b].join(";"));b=e.join("%0A");e=moment().format()+"_Data.csv";$.browser.msie?(b=new Blob([b],{type:"text/csv;charset=utf-8;"}),navigator.msSaveBlob(b,e)):(c=document.createElement("a"),c.href="data:text/csv;charset=utf-8,"+b,c.target="_blank",
c.download=e,document.body.appendChild(c),c.click())};
